function initChart(){var a=new Date,c=a.getFullYear(),a=a.getMonth();null!=yearG&&"null"!=yearG||(yearG=c);null!=monthG&&"null"!=monthG||(monthG=a+1+"");null!=sumByG&&"null"!=sumByG||(sumByG=$("#SumBy").val());$("#SumBy").val(sumByG);$("#SumBy").val();listMonths();listYears()}
function goUrl(){var a=$("#SumBy").val(),c=$("#financeYear").val(),d=$("#financeMonth").val(),f={graphset:[{type:"mixed","background-color":"#FFFFFF",stacked:"1",chart:{margin:"30 60 30 80"},labels:[{text:"\u0e1e\u0e31\u0e19\u0e1a\u0e32\u0e17",bold:!0,"font-size":12,x:"60",y:"0"}],legend:{"background-color":"#FFFFFF","border-width":"2px","border-color":"#4C77B6",margin:"70 0 0 885",layout:"x1",item:{"font-color":"#000000"}},guide:{shared:!0},tooltip:{visible:!1},"scale-x":{values:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),
guide:{"line-width":1,alpha:1},tick:{"line-width":3},item:{"font-color":"#000000"}},"scale-y":{format:"%v",decimals:0,"decimals-separator":".","thousands-separator":",",guide:{"line-width":1,alpha:1},tick:{"line-width":3}},"scale-y-2":{format:"%v%",guide:{"line-width":0,alpha:0},tick:{"line-width":3}},series:[{type:"bar",values:[],text:"ActualYTD 09","background-color":"#66CC00",stacked:0},{type:"bar",values:[],text:"ActualYTD 10","background-color":"#EEEE00",stacked:0},{type:"bar",values:[],text:"Budget",
"background-color":"#696969",stacked:0},{type:"line",values:[],text:"%Variance YTD",scales:"scale-x,scale-y-2",stacked:0,"line-color":"#E46C0A",aspect:"spline",marker:{visible:!1}},{type:"line",values:[],text:"%GrowthYTD",scales:"scale-x,scale-y-2","line-color":"#4F81BD",stacked:0,aspect:"spline",marker:{visible:!1}}]}]},e={graphset:[{type:"mixed","background-color":"#FFFFFF",stacked:"1",chart:{margin:"30 60 30 80"},labels:[{text:"\u0e1e\u0e31\u0e19\u0e1a\u0e32\u0e17",bold:!0,"font-size":12,x:"60",
y:"0"}],legend:{"background-color":"#FFFFFF","border-width":"2px","border-color":"#4C77B6",margin:"70 0 0 885",layout:"x1",item:{"font-color":"#000000"}},guide:{shared:!0},tooltip:{visible:!1},"scale-x":{values:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),guide:{"line-width":1,alpha:1},tick:{"line-width":3},item:{"font-color":"#000000"}},"scale-y":{format:"%v",decimals:0,"decimals-separator":".","thousands-separator":",",guide:{"line-width":1,alpha:1},tick:{"line-width":3}},"scale-y-2":{format:"%v%",
guide:{"line-width":0,alpha:0},tick:{"line-width":3},item:{"font-color":"#000000"}},series:[{type:"bar",values:[],text:"ActualYTD 09","background-color":"#66CC00",stacked:0},{type:"bar",values:[],text:"ActualYTD 10","background-color":"#EEEE00",stacked:0},{type:"bar",values:[],text:"Budget","background-color":"#696969",stacked:0},{type:"line",values:[],text:"%Variance YTD",scales:"scale-x,scale-y-2",stacked:0,"line-color":"#E46C0A",aspect:"spline",marker:{visible:!1}},{type:"line",values:[],text:"%GrowthYTD",
scales:"scale-x,scale-y-2","line-color":"#4F81BD",stacked:0,aspect:"spline",marker:{visible:!1}}]}]};if("6"==a||"7"==a){var g=[],h=[],i=[],j=[],k=[];$("#g1").html('<img src="'+_path+'/Dashboard/images/loading.gif"/>');$("#g1_legend").html("");BalanceScorecardAjax.getFinancial_YTD_Monthly_Summary(c,d,a,{callback:function(b){if(null!=b&&0<b.length){for(var a=0;a<b.length;a++)g.push(null!=b[a].sumLastYearActualMONTHLY&&0<b[a].sumLastYearActualMONTHLY.length?b[a].sumLastYearActualMONTHLY:"0.00"),h.push(null!=
b[a].sumThisYearActualMonthly&&0<b[a].sumThisYearActualMonthly.length?b[a].sumThisYearActualMonthly:"0.00"),i.push(null!=b[a].sumThisYearBudgetMONTHLY&&0<b[a].sumThisYearBudgetMONTHLY.length?b[a].sumThisYearBudgetMONTHLY:"0.00"),j.push(null!=b[a].percentVarianceMONTHLY&&0<b[a].percentVarianceMONTHLY.length?b[a].percentVarianceMONTHLY:"0.00"),k.push(null!=b[a].percentGrowthMONTHLY&&0<b[a].percentGrowthMONTHLY.length?b[a].percentGrowthMONTHLY:"0.00");f.graphset[0].series[0].values=g;f.graphset[0].series[1].values=
h;f.graphset[0].series[2].values=i;f.graphset[0].series[3].values=j;f.graphset[0].series[4].values=k;$("#g1").html("");$("#g1_legend").html('<img src="'+_path+'/Dashboard/images/legend_Y-M.jpg"/>');render_zingchart("g1",f)}else $("#g1").html(""),$("#g1_legend").html("")}});render_financialIndication(c,d,"1");for(var l=0;l<tabsG.length;l++)reder_tab_data(c,d,tabsG[l],a,e)}else location.href=_path+"/Dashboard/"+urlG+".jsp?y="+c+"&m="+d+"&sb="+a}
function reder_tab_data(a,c,d,f,e){var g=[],h=[],i=[],j=[],k=[];$("#"+d+"_tab").html('<img src="'+_path+'/Dashboard/images/loading.gif"/>');$("#"+d+"_legend").html("");BalanceScorecardAjax.getFinancial_YTD_Monthly_Tab(a,c,d,f,{callback:function(a){if(null!=a&&0<a.length){for(var b=0;b<a.length;b++)g.push(null!=a[b].sumLastYearActualMONTHLY&&0<a[b].sumLastYearActualMONTHLY.length?a[b].sumLastYearActualMONTHLY:"0.00"),h.push(null!=a[b].sumThisYearActualMonthly&&0<a[b].sumThisYearActualMonthly.length?
a[b].sumThisYearActualMonthly:"0.00"),i.push(null!=a[b].sumThisYearBudgetMONTHLY&&0<a[b].sumThisYearBudgetMONTHLY.length?a[b].sumThisYearBudgetMONTHLY:"0.00"),j.push(null!=a[b].percentVarianceMONTHLY&&0<a[b].percentVarianceMONTHLY.length?a[b].percentVarianceMONTHLY:"0.00"),k.push(null!=a[b].percentGrowthMONTHLY&&0<a[b].percentGrowthMONTHLY.length?a[b].percentGrowthMONTHLY:"0.00");e.graphset[0].series[0].values=g;e.graphset[0].series[1].values=h;e.graphset[0].series[2].values=i;e.graphset[0].series[3].values=
j;e.graphset[0].series[4].values=k;$("#"+d+"_tab").html("");$("#"+d+"_legend").html('<img src="'+_path+'/Dashboard/images/legend_Y-M.jpg"/>');render_zingchart(d+"_tab",e)}else $("#"+d+"_tab").html(""),$("#"+d+"_legend").html("")}})}
function render_financialIndication(a,c,d){var f='<table id=table-data1 width=100%>     <tr><th class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active" style="height:35px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Financial Indicator&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</th></tr></table><table id=table-data width=100%>    <tr>        <th bgcolor=#CD853F colspan=3><font color="#FFFFFF">'+monthNameG[parseInt(c)-1]+" "+a+"</font></th>    </tr>",e,g;BalanceScorecardAjax.getFinancialIndication(a,
c,d,{callback:function(a){if(null!=a&&0<a.length)for(var c=0;c<a.length;c++)if(f=f+"<tr><th colspan=3>"+a[c].ratioGroupName+"</th></tr>",e=a[c].financialIndicationDTO,null!=e&&0<e.length)for(var d=0;d<e.length;d++)g="",null!=e[d].trendFlag&&("I"==e[d].trendFlag&&(g="<img src=images/up1.png>"),"D"==e[d].trendFlag&&(g="<img src=images/down1.png>")),f=f+"<tr><td>"+e[d].ratioName+"</td><td>"+g+"</td><td>"+e[d].thisPeriodValue+"</td></tr>";f+="</table>";$("#fnancial_indicator_Display").html(f);$("#tabs-ratio").tabs()}})}
function render_zingchart(a,c){zingchart.render({id:a,width:850,height:270,data:c})}function listYears(){var a='<font size="3"> \u0e1b\u0e35: </font>';BalanceScorecardAjax.listYears({callback:function(c){a+='<select name="financeYear" id="financeYear" >';if(null!=c&&0<c.length)for(var d=0;d<c.length;d++)a=a+'<option value="'+c[d]+'" '+(yearG==c[d]?' selected="selected"':"")+">"+c[d]+"</option>";a+="</select>";$("#financeYearElement").html(a);goUrl()}})}
function listMonths(){var a;a='<font size="3"> \u0e40\u0e14\u0e37\u0e2d\u0e19: </font><select name="financeMonth" id="financeMonth" >';if(null!=monthKeyG&&0<monthKeyG.length)for(var c=0;c<monthKeyG.length;c++)a=a+'<option value="'+monthKeyG[c]+'" '+(monthG==monthKeyG[c]?' selected="selected"':"")+">"+monthNameG[c]+"</option>";$("#financeMonthElement").html(a+"</select>")};
