function initChart(){var a=new Date,c=a.getFullYear(),a=a.getMonth();null!=yearG&&"null"!=yearG||(yearG=c);null!=monthG&&"null"!=monthG||(monthG=a+1+"");null!=sumByG&&"null"!=sumByG||(sumByG=$("#SumBy").val());$("#SumBy").val(sumByG);sumByG=$("#SumBy").val();listMonths();listYears()}
function render_financialIndication(a,c,b,e){var d='<table id=table-data1 width=220px>     <tr><th class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active" style="height:35px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Financial Indicator&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</th></tr></table><table id=table-data width=100%>    <tr>        <th bgcolor=#CD853F colspan=3><font color="#FFFFFF">'+monthNameG[parseInt(c)-1]+" "+a+" vs "+monthNameG[parseInt(c)-1]+" "+(parseInt(a)-1)+"</font></th>    </tr>",
f,h;BalanceScorecardAjax.getFinancialIndication(a,c,e,{callback:function(a){if(null!=a&&0<a.length)for(var c=0;c<a.length;c++)if(d=d+"<tr><th colspan=3>"+a[c].ratioGroupName+"</th></tr>",f=a[c].financialIndicationDTO,null!=f&&0<f.length)for(var b=0;b<f.length;b++)h="",null!=f[b].trendFlag&&("I"==f[b].trendFlag&&(h="<img src=images/up1.png>"),"D"==f[b].trendFlag&&(h="<img src=images/down1.png>")),d=d+"<tr><td>"+f[b].ratioName+"</td><td>"+h+"</td><td>"+f[b].thisPeriodValue+"</td></tr>";d+="</table>";
$("#fnancial_indicator_Display").html(d);$("#tabs-ratio").tabs()}})}function render_zingchart(a,c,b,e){zingchart.render({id:a,width:b,height:e,data:c})}
function listYears(){var a='<font size="3"> \u0e1b\u0e35: </font>';BalanceScorecardAjax.listYears({callback:function(c){a+='<select name="financeYear" id="financeYear" >';if(null!=c&&0<c.length)for(var b=0;b<c.length;b++)a=a+'<option value="'+c[b]+'" '+(yearG==c[b]?' selected="selected"':"")+">"+c[b]+"</option>";a+="</select>";$("#financeYearElement").html(a);goUrl()}})}
function listMonths(){var a;a='<font size="3"> \u0e40\u0e14\u0e37\u0e2d\u0e19: </font><select name="financeMonth" id="financeMonth" >';if(null!=monthKeyG&&0<monthKeyG.length)for(var c=0;c<monthKeyG.length;c++)a=a+'<option value="'+monthKeyG[c]+'" '+(monthG==monthKeyG[c]?' selected="selected"':"")+">"+monthNameG[c]+"</option>";$("#financeMonthElement").html(a+"</select>")}
function goUrl(){var a=$("#SumBy").val(),c=$("#financeYear").val(),b=$("#financeMonth").val();if("6"==a||"7"==a)location.href=_path+"/Dashboard/"+urlG+".jsp?y="+c+"&m="+b+"&sb="+a;else{for(var e=0;e<gTypeG.length;e++)render_gtype_data(c,b,gTypeIdG[e],gTypeG[e],e,a,null);for(e=0;e<tabsG.length;e++)render_gtab_data(c,b,tabsG[e],a),render_mix_data("g"+tabsG[e],c,b,a,tabsG[e]);render_financialIndication(c,b,a,"1");render_mix_data("g2",c,b,a,null);render_pile(c,b,a)}}
function parseDouble(a){"string"==typeof a&&(a=a.match(/^-?\d*/)[0]);return!isNaN(parseInt(a))?1*a:NaN}
function render_pile(a,c,b){var e={graphset:[{type:"pie","background-color":"#FFFFFF",chart:{margin:"0 0 45 0","padding-top":"0px"},legend:{"background-color":"#FFFFFF","border-width":"2px","border-color":"#4C77B6",layout:"2x",x:10,y:265,width:400},scale:{"size-factor":0.8},tooltip:{padding:"6","border-radius":"6"},plot:{"ref-angle":0,"value-box":{placement:"in",text:"%v%"}},series:[{text:"Restaurant",values:[17.42],"tooltip-text":"%t: 273,950"},{text:"Bakery Shop",values:[21.49],"tooltip-text":"%t: 312,060"},
{text:"Specialty",values:[15.35],"tooltip-text":"%t: 259,923"},{text:"Trading",values:[22.75],"tooltip-text":"%t: 365,034"},{text:"Caterman",values:[12.67],"tooltip-text":"%t: 212,355"},{text:"Other",values:[10.32],"tooltip-text":"%t: 152,716"}]}]};$("#g3").html('<img src="'+_path+'/Dashboard/images/loading.gif"/>');BalanceScorecardAjax.getPile(a,c,b,{callback:function(a){if(null!=a&&0<a.length){for(var c=0,b=0;b<a.length;b++)c+=Number(a[b].thisActual);for(b=0;b<a.length;b++)0!=c?(e.graphset[0].series[b]["tooltip-text"]=
"%t: "+Number(a[b].thisActual).toFixed(2),e.graphset[0].series[b].values=[100*(Number(a[b].thisActual)/c).toFixed(2)]):(e.graphset[0].series[b]["tooltip-text"]="%t: 0",e.graphset[0].series[b].values=[0]);$("#g3").html("");render_zingchart("g3",e,420,320)}else $("#g3").html("")}})}
function render_mix_data(a,c,b,e,d){$("#"+a).html('<img src="'+_path+'/Dashboard/images/loading.gif"/>');$("#"+a+"_legend").html("");BalanceScorecardAjax.getFD1_2_4_percent(c,b,e,d,{callback:function(b){if(null!=b&&3==b.length){var c={graphset:[{type:"mixed","background-color":"#FFFFFF",chart:{margin:"20 20 30 50"},stacked:"1",plot:{"bars-space-left":"25%","bars-space-right":"25%","bar-width":"25px"},"scale-x":{values:["Last Year","Actual","Budget"],guide:{"line-width":1,alpha:1},tick:{"line-width":3}},
"scale-y":{"min-value":0,format:"%v%",guide:{"line-width":1,alpha:1},tick:{"line-width":3}},series:[{type:"bar",values:[54.27,43.74,54.27],"background-color":"deepskyblue",text:"\u0e04\u0e48\u0e32\u0e43\u0e0a\u0e49\u0e08\u0e48\u0e32\u0e22\u0e01\u0e32\u0e23\u0e02\u0e32\u0e22\u0e41\u0e25\u0e30\u0e1a\u0e23\u0e34\u0e2b\u0e32\u0e23"},{type:"bar",values:[32.88,29.85,32.88],"background-color":"goldenrod",text:"\u0e15\u0e49\u0e19\u0e17\u0e38\u0e19\u0e02\u0e32\u0e22"}]}]},e=[],d=[];$("#"+a).html("");$("#"+
a+"_legend").html("");for(var g=1;3>g;g++){var i,j,k;i=null!=b[0].sumLastYearActualMONTHLY&&0<b[0].sumLastYearActualMONTHLY.length?0==parseDouble(b[0].sumLastYearActualMONTHLY)?0:100*(parseDouble(b[g].sumLastYearActualMONTHLY)/parseDouble(b[0].sumLastYearActualMONTHLY)):0;j=null!=b[0].sumThisYearActualMonthly&&0<b[0].sumThisYearActualMonthly.length?0==parseDouble(b[0].sumThisYearActualMonthly)?0:100*(parseDouble(b[g].sumThisYearActualMonthly)/parseDouble(b[0].sumThisYearActualMonthly)):0;k=null!=
b[0].sumThisYearBudgetMONTHLY&&0<b[0].sumThisYearBudgetMONTHLY.length?0==parseDouble(b[0].sumThisYearBudgetMONTHLY)?0:100*(parseDouble(b[g].sumThisYearBudgetMONTHLY)/parseDouble(b[0].sumThisYearBudgetMONTHLY)):0;1==g?(e.push(i),e.push(j),e.push(k)):(d.push(i),d.push(j),d.push(k))}c.graphset[0].series[0].values=e;c.graphset[0].series[1].values=d;render_zingchart(a,c,290,229)}}})}
function render_gtab_data(a,c,b,e){for(var d=0;d<gTypeG.length;d++)render_gtype_data(a,c,gTypeIdG[d]+"_"+b,gTypeG[d],d,e,b)}
function render_gtype_data(a,c,b,e,d,f,h){$("#"+b).html('<img src="'+_path+'/Dashboard/images/loading.gif"/>');$("#"+b+"_legend").html("");var l=[],m=[],g=[],i=[];BalanceScorecardAjax.getFD1_2_4(a,c,d,f,h,{callback:function(a){if(null!=a&&0<a.length){for(var c={graphset:[{type:"mixed","background-color":"#FFFFFF",chart:{margin:"25 25 35 50"},labels:[{text:"-2.31%",hook:"node:plot=1,index=0","background-color":"red",color:"white","border-width":5,"border-color":"red",bold:!0},{text:"12.79%",hook:"node:plot=2,index=0",
"background-color":"blue",color:"white","border-width":5,"border-color":"blue",bold:!0},{text:"\u0e25\u0e49\u0e32\u0e19 (\u0e1a\u0e32\u0e17)",bold:!0,x:"15",y:"0"}],plot:{"tooltip-text":"%v","bars-space-left":"15%","bars-space-right":"15%"},"scale-x":{values:[],guide:{"line-width":1,alpha:1},tick:{"line-width":3},item:{"font-color":"#000000"}},"scale-y":{"min-value":0,format:"%v",guide:{"line-width":1,alpha:1},tick:{"line-width":3},item:{"font-color":"#000000"}},series:[{type:"bar",values:[],text:"Actual",
"background-color":"#66CC00"},{type:"bar",values:[],text:"Last Year","background-color":"#EEEE00"},{type:"bar",values:[],text:"Budget","background-color":"#696969"}]}]},d=0;d<a.length;d++)m.push(null!=a[d].sumLastYearActualMONTHLY&&0<a[d].sumLastYearActualMONTHLY.length?a[d].sumLastYearActualMONTHLY:"0.00"),g.push(null!=a[d].sumThisYearActualMonthly&&0<a[d].sumThisYearActualMonthly.length?a[d].sumThisYearActualMonthly:"0.00"),i.push(null!=a[d].sumThisYearBudgetMONTHLY&&0<a[d].sumThisYearBudgetMONTHLY.length?
a[d].sumThisYearBudgetMONTHLY:"0.00");$("#"+b).html("");$("#"+b+"_legend").html("");l.push(e);c.graphset[0].series[0].values=m;c.graphset[0].series[1].values=g;c.graphset[0].series[2].values=i;c.graphset[0]["scale-x"].values=l;render_zingchart(b,c,190,230)}else $("#"+b).html(""),$("#"+b+"_legend").html("")}})};
